export const CONTRACT_CAST_VOTE = 'CONTRACT_CAST_VOTE'
export const CONTRACT_GET_CANDIDATES = 'CONTRACT_GET_CANDIDATES'
export const CONTRACT_LOAD = 'CONTRACT_LOAD'
export const WEB3_LOAD = 'WEB3_LOAD'